### PR TITLE
simple authorization framework

### PR DESCRIPTION
**Pull request by jaypipes**
Investigated using the casbin library but eventually went with a
homegrown solution that I felt had a better fit for the types of
authorization functions I was looking for.

This first set of patches add the protobuffer definitions for the messages
involved in the authz system and the infrastructure for plumbing into
the IAM server. The pkg/authz package contains an Authz struct that
will be used to hang caching and possible backend storage adaption
from. The Context struct contains the Session protobuffer message
pointer for the user and a Permissions protobuffer message that will be
constructed by the authz package when a request is received.

Adds a simple adapter interface to Authz struct that caches permissions
for sessions for a configurable amount of time. This interface is
tested in the authz_test.go file, however I've left the "load from data
store" implementation as a TODO in the "real" cache driver.

Issue #11

### CODE REVIEW

**Comment by hsluoyz** [comment]
Hi,

I'm the maintainer of the [Casbin](https://github.com/casbin/casbin) library. May I ask the reason that you finally didn't choose to use Casbin? It will be regarded as a very valuable suggestion for the project. Thanks:)

**Comment by jaypipes** [comment]
Hi @hsluoyz!

I did take a long, hard look at Casbin and tried using it for my purposes. Perhaps I was unable to understand the Casbin code properly, but here are the things I ran into that made the library less suitable for my needs:

1) All data in the Procession system that is persisted in any form is in a Google Protobuffer message format. I made this decision so that Procession can be developed in more languages than just Golang. I would have needed to write a type of adapter layer for Casbin to translate between Casbin's data model and these GPB messages. I didn't want to go through this trouble.

2) I couldn't figure out how to get Casbin to model a "if owner of resource X OR user has permission Y" type of policy. Procession's objects are created by users and those "owning users" should always be able to do things against those objects. I could not understand how to model this type of policy using the Casbin configuration files.

3) If the Procession user shares access to a resource to another user, I wanted to be able to model that in the RBAC/authz policy (that's what the ScopedPermission stuff is in the authz.proto file in this patchset is for). I wasn't sure how to model this in Casbin's configuration language.

4) I don't want to have configuration files for defining models. If Casbin would allow creation of its Model structures using Golang code, that would be cool. I'd be quite happy to contribute this feature to Casbin in the future. :)

Best,
-jay

**Comment by hsluoyz** [comment]
Hi @jaypipes ,

Thanks for the detailed investigation for this project. I will try to answer your questions.

> 1. All data in the Procession system that is persisted in any form is in a Google Protobuffer message format. I made this decision so that Procession can be developed in more languages than just Golang. I would have needed to write a type of adapter layer for Casbin to translate between Casbin's data model and these GPB messages. I didn't want to go through this trouble.

If you want to use Casbin to persist the policy rules, you have to design a Casbin storage adapter. We already have MySQL, Cassandra, Consul adapters, but still no one for PB. But implementing it is not that difficult, only two functions ``LoadPolicy()`` and ``SavePolicy()`` are needed.

Another option is not using Casbin persistence at all. Add and remove the rules at run-time via Casbin API. And store the rules at your side (which you also need to do by DIY). In this way, Casbin doesn't complicate things at least. 

> 2. I couldn't figure out how to get Casbin to model a "if owner of resource X OR user has permission Y" type of policy. Procession's objects are created by users and those "owning users" should always be able to do things against those objects. I could not understand how to model this type of policy using the Casbin configuration files.

The focus here is the owner feature. It's very easy to express ``owner can do anything to a resource he owns`` in Casbin. You can specify the owner attribute in the matcher, which can be used to compare with other values. See the ABAC example at: https://github.com/casbin/casbin/blob/master/examples/abac_model.conf

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.Owner
```

The above model means if the user (r.sub) equals the owner of the resource (r.obj.Owner), then allow. The Owner is a property in the Resource struct. The definition is like: 

```go
type testResource struct {
	Name   string
	Owner string
}
```

> 3. If the Procession user shares access to a resource to another user, I wanted to be able to model that in the RBAC/authz policy (that's what the ScopedPermission stuff is in the authz.proto file in this patchset is for). I wasn't sure how to model this in Casbin's configuration language.

I saw your ScopedPermission but it seems to be the permissions within an organization instead of sharing resource to another user. The inter-user resource sharing depends on how you define the ID of the resource. I didn't find how the resource ID is defined in the code (clarify me if I'm wrong). Is it a global ID across all users? or a local ID that is only recognized inside a user/org? They are different cases. 

And BTW, I found I can't compile the code. It seems that ``github.com/jaypipes/procession/proto`` has no Go source files.

> 4. I don't want to have configuration files for defining models. If Casbin would allow creation of its Model structures using Golang code, that would be cool. I'd be quite happy to contribute this feature to Casbin in the future. :)

I thought everyone would love the configuration file:(

Good news is, the model can be constructed in code manually now, see example: [TestCreateModelManually](https://github.com/casbin/casbin/blob/master/enforcer_test.go#L31-L52).

```go
func TestCreateModelManually(t *testing.T) {
	e := NewEnforcer()

	model := make(model.Model)
	model.AddAssertion("r", "r", "sub, obj, act")
	model.AddAssertion("p", "p", "sub, obj, act")
	model.AddAssertion("e", "e", "some(where (p.eft == allow))")
	model.AddAssertion("m", "m", "r.sub == p.sub && r.obj == p.obj && r.act == p.act")
	e.SetModel(model)

	a := persist.NewFileAdapter("examples/basic_policy.csv")
	a.LoadPolicy(e.GetModel())

	testEnforce(t, e, "alice", "data1", "read", true)
	testEnforce(t, e, "alice", "data1", "write", false)
	testEnforce(t, e, "alice", "data2", "read", false)
	testEnforce(t, e, "alice", "data2", "write", false)
	testEnforce(t, e, "bob", "data1", "read", false)
	testEnforce(t, e, "bob", "data1", "write", false)
	testEnforce(t, e, "bob", "data2", "read", false)
	testEnforce(t, e, "bob", "data2", "write", true)
}
```

**Comment by jaypipes** [comment]
"And BTW, I found I can't compile the code. It seems that github.com/jaypipes/procession/proto has no Go source files."

@hsluoyz: run `make generated` in the root directory :)

**Comment by jaypipes** [comment]
"The above model means if the user (r.sub) equals the owner of the resource (r.obj.Owner), then allow. The Owner is a property in the Resource struct. The definition is like:"

@hsluoyz How do I structure a policy rule that is an "OR"?

For instance, something like this?

```
m = (r.sub == r.obj.Owner OR r.sub in [ <some groups> ] OR r.obj.isSharedWith(r.sub)
```

**Comment by hsluoyz** [comment]
@jaypipes You can simply use ``||`` to represent "OR"

``m = r.sub == r.obj.Owner || g(r.sub, p.sub) || isSharedWith(r.obj, r.sub)``

``g()`` function determines whether r.sub has the role/group p.sub. See the RBAC example: https://github.com/casbin/casbin/blob/master/examples/rbac_model.conf

``isSharedWith`` can be defined as an external function, so you can provide your logic there: https://github.com/casbin/casbin/blob/master/Model.md#functions-in-matchers

I don't know how you want to design the logic of ``isSharedWith``, but if it can be expressed by Casbin model, you can write the logic in Casbin too.

**Pull request merged**
